"""
Safe execution of Python code for Plotly chart generation.

Executes user-generated code in an isolated subprocess with:
- Timeout to prevent infinite loops
- Restricted imports (plotly, pandas, numpy)
- Captured stdout/stderr
- Descriptive error messages
"""

from __future__ import annotations

import io
import json
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from langchain_core.messages import ToolMessage
from langgraph.types import Command
from langchain.tools import ToolRuntime, tool

from src.config import CHART_AGENT_CONFIG


@dataclass
class ExecutionResult:
    """Result of code execution."""

    success: bool
    figure_json: dict[str, Any] | None = None
    figure_html: str | None = None
    stdout: str = ""
    stderr: str = ""
    error_message: str | None = None


# Wrapper script that runs in subprocess - receives code via stdin
_EXECUTOR_SCRIPT = """
import io
import json
import os
import sys
import traceback

# Restricted globals - only allow chart-related imports
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
import pandas as pd
import numpy as np

_globals = {
    "px": px,
    "go": go,
    "pio": pio,
    "pd": pd,
    "pandas": pd,
    "np": np,
    "numpy": np,
    "__builtins__": __builtins__,
}

# Pre-load df if data file path provided via env
_data_path = os.environ.get("PLOTLY_EXEC_DATA_CSV")
if _data_path and os.path.exists(_data_path):
    _globals["df"] = pd.read_csv(_data_path)

def main():
    code = sys.stdin.read()
    stdout_capture = io.StringIO()
    stderr_capture = io.StringIO()
    
    old_stdout, old_stderr = sys.stdout, sys.stderr
    sys.stdout, sys.stderr = stdout_capture, stderr_capture
    
    try:
        exec(code, _globals)
    except Exception as e:
        sys.stdout, sys.stderr = old_stdout, old_stderr
        error_msg = "".join(traceback.format_exception(type(e), e, e.__traceback__))
        result = {
            "success": False,
            "error": str(e),
            "traceback": error_msg,
            "stdout": stdout_capture.getvalue(),
            "stderr": stderr_capture.getvalue(),
        }
        print(json.dumps(result), file=sys.stderr)
        sys.exit(1)
    
    sys.stdout, sys.stderr = old_stdout, old_stderr
    
    # Look for figure in common variable names
    fig = _globals.get("fig") or _globals.get("figure") or _globals.get("chart")
    
    if fig is None:
        result = {
            "success": False,
            "error": "No figure found. Code must assign the Plotly figure to a variable named 'fig', 'figure', or 'chart'.",
            "stdout": stdout_capture.getvalue(),
            "stderr": stderr_capture.getvalue(),
        }
        print(json.dumps(result), file=sys.stderr)
        sys.exit(1)
    
    try:
        fig_json = pio.to_json(fig)
        fig_dict = json.loads(fig_json)
    except Exception as e:
        result = {
            "success": False,
            "error": f"Failed to serialize figure: {e}",
            "stdout": stdout_capture.getvalue(),
            "stderr": stderr_capture.getvalue(),
        }
        print(json.dumps(result), file=sys.stderr)
        sys.exit(1)
    
    result = {
        "success": True,
        "figure_json": fig_dict,
        "figure_html": pio.to_html(fig),
        "stdout": stdout_capture.getvalue(),
        "stderr": stderr_capture.getvalue(),
    }
    print(json.dumps(result))

main()
"""


def _truncate_error_message(msg: str, max_lines: int | None = None) -> str:
    """Truncate an error message for LLM consumption.

    Keeps the exception header and the tail of the traceback — which is
    where the user code's failing line normally lives — so the model has
    enough context to actually fix its own bug on retry.
    """
    if max_lines is None:
        max_lines = CHART_AGENT_CONFIG.get("code_mode_error_context_lines", 8)

    lines = [ln.rstrip() for ln in msg.splitlines() if ln.strip()]
    if len(lines) <= max_lines:
        return "\n".join(lines)

    # Always keep the first line (exception header) and the last
    # max_lines-1 lines of the traceback (where the user code failure is).
    head = lines[:1]
    tail = lines[-(max_lines - 1):]
    return "\n".join(head + tail)


def execute_plotly_code(
    code: str,
    *,
    timeout_seconds: float = 30.0,
    return_html: bool = True,
    data_csv: str | None = None,
    max_error_lines: int | None = None,
) -> ExecutionResult:
    """
    Execute Python code that generates a Plotly chart in a safe subprocess.

    The code must assign the Plotly figure to a variable named `fig`, `figure`, or `chart`.
    Only plotly, pandas, and numpy are available by default.

    Args:
        code: Python code to execute (e.g., generated by a chart agent).
        timeout_seconds: Maximum execution time. Default 30 seconds.
        return_html: If True, include figure HTML in result. Set False to reduce payload size.
        data_csv: Optional CSV string. If provided, a DataFrame `df` is pre-loaded for the code.
        max_error_lines: Max lines for error_message (default 2). Keeps errors compact for LLM feedback.

    Returns:
        ExecutionResult with success flag, figure (JSON/HTML), stdout, stderr, and error message.
    """
    env = None
    data_file_path = None
    if data_csv is not None:
        with tempfile.NamedTemporaryFile(
            mode="w",
            suffix=".csv",
            delete=False,
        ) as f:
            f.write(data_csv)
            data_file_path = f.name
        env = {**__import__("os").environ, "PLOTLY_EXEC_DATA_CSV": data_file_path}
    with tempfile.NamedTemporaryFile(
        mode="w",
        suffix=".py",
        delete=False,
    ) as f:
        script_path = f.name
        f.write(_EXECUTOR_SCRIPT)

    try:
        result = subprocess.run(
            [sys.executable, script_path],
            input=code,
            capture_output=True,
            text=True,
            timeout=timeout_seconds,
            env=env,
        )
    except subprocess.TimeoutExpired:
        return ExecutionResult(
            success=False,
            error_message=f"Execution timed out after {timeout_seconds} seconds. "
            "The code may have an infinite loop or is taking too long.",
        )
    except Exception as e:
        return ExecutionResult(
            success=False,
            error_message=f"Failed to run code: {e}",
        )
    finally:
        Path(script_path).unlink(missing_ok=True)
        if data_file_path:
            Path(data_file_path).unlink(missing_ok=True)

    # Result is printed to stdout on success, stderr on failure
    output = result.stdout or result.stderr or ""

    try:
        # Try to parse JSON from the last line (in case of print statements)
        lines = output.strip().split("\n")
        json_line = lines[-1] if lines else ""
        data = json.loads(json_line)
    except json.JSONDecodeError:
        msg = (
            f"Execution produced no valid result. Exit code: {result.returncode}. "
            f"Stdout: {(result.stdout or '')[:200]}. Stderr: {(result.stderr or '')[:200]}."
        )
        return ExecutionResult(
            success=False,
            stdout=result.stdout,
            stderr=result.stderr,
            error_message=_truncate_error_message(msg, max_error_lines),
        )

    if not data.get("success", False):
        error = data.get("error", "Unknown error")
        traceback_str = data.get("traceback", "")
        msg = f"{error}"
        if traceback_str:
            msg += f"\n\nTraceback:\n{traceback_str}"
        msg = _truncate_error_message(msg, max_error_lines)
        return ExecutionResult(
            success=False,
            stdout=data.get("stdout", ""),
            stderr=data.get("stderr", ""),
            error_message=msg,
        )

    return ExecutionResult(
        success=True,
        figure_json=data.get("figure_json"),
        figure_html=data.get("figure_html") if return_html else None,
        stdout=data.get("stdout", ""),
        stderr=data.get("stderr", ""),
    )


# --- Execute Chart Tool ---
@tool
def data_not_provided(runtime: ToolRuntime) -> str:
    """
    Use this tool when the data is not provided in chart description.
    """
    tool_message = [
        ToolMessage(
            content="Data is not provided, please provide the data and execute again.",
            name="data_not_provided",
            tool_call_id=runtime.tool_call_id,
        )
    ]
    return Command(update={"data_provided": False, "messages": tool_message})


@tool
def execute_plotly_chart_python_code(code: str, runtime: ToolRuntime) -> str:
    """
    Execute Python code that generates a Plotly chart.

    Use this tool when you have Python code (using plotly, pandas, numpy) that creates
    a chart. The code must assign the Plotly figure to a variable named 'fig', 'figure',
    or 'chart'.

    Args:
        code: Python code to execute (e.g., using plotly.express or plotly.graph_objects).DO NOT have code line to show image like fig.show() in the code.
    """
    num_code_correction = runtime.state.get("num_code_correction", 0)
    result = execute_plotly_code(
        code,
        timeout_seconds=30.0,
    )

    if result.success:
        tool_message = [
            ToolMessage(
                content=f"Successfully Executed Python Code and generated the chart.",
                name="execute_plotly_chart_python_code",
                tool_call_id=runtime.tool_call_id,
            )
        ]
        return Command(
            update={
                "chart_json": result.figure_json,
                "is_code_error": False,
                "num_code_correction": num_code_correction + 1,
                "data_provided": True,
                "messages": tool_message,
                "python_code": code,
            }
        )
    else:
        tool_message = [
            ToolMessage(
                content=f"Failed to execute Python Code due to following error, fix the code and execute again:\n{result.error_message}",
                name="execute_plotly_chart_python_code",
                tool_call_id=runtime.tool_call_id,
            )
        ]
        return Command(
            update={
                "is_code_error": True,
                "num_code_correction": num_code_correction + 1,
                "data_provided": True,
                "messages": tool_message,
                "python_code": code,
            }
        )
